---
version: 1
schedule:
  # Run every minute
  type: cron
  interval: "0 * * * * *"
workflow:
  collect:
    metrics:
      /rabbitmq/nodes/*/fd_used: {}
      /rabbitmq/nodes/*/mem_used: {}
      /rabbitmq/nodes/*/memory/total: {}
      /rabbitmq/nodes/*/memory/mgmt_db: {}
      /rabbitmq/nodes/*/memory/connection_channels: {}
      /rabbitmq/nodes/*/proc_used: {}
      /rabbitmq/nodes/*/sockets_used: {}
      /rabbitmq/exchanges/*/*/message_stats/publish_in: {}
      /rabbitmq/exchanges/*/*/message_stats/publish_out: {}
      /rabbitmq/exchanges/*/*/message_stats/publish_in_details/rate: {}
      /rabbitmq/exchanges/*/*/message_stats/publish_out_details/rate: {}
      /rabbitmq/queues/*/*/consumers: {}
      /rabbitmq/queues/*/*/memory: {}
      /rabbitmq/queues/*/*/message_stats/publish: {}
      /rabbitmq/queues/*/*/message_stats/publish_details/rate: {}
      /rabbitmq/queues/*/*/messages: {}
      /rabbitmq/queues/*/*/messages_details/rate: {}
      /rabbitmq/queues/*/*/messages_ready: {}
      /rabbitmq/queues/*/*/messages_ready_details/rate: {}
      /rabbitmq/queues/*/*/messages_unacknowledged: {}
      /rabbitmq/queues/*/*/messages_unacknowledged_details/rate: {}
      /rabbitmq/vhosts/*/messages: {}
      /rabbitmq/vhosts/*/messages_ready: {}
      /rabbitmq/vhosts/*/messages_ready_details/rate: {}
      /rabbitmq/vhosts/*/message_stats/publish: {}
      /rabbitmq/vhosts/*/message_stats/publish_details/rate: {}
      /rabbitmq/vhosts/*/messages_details/rate: {}
      /rabbitmq/vhosts/*/messages_unacknowledged: {}
      /rabbitmq/vhosts/*/messages_unacknowledged_details/rate: {}
      # All available metrics
      #/rabbitmq/exchanges/*/*/message_stats/confirm: {}
      #/rabbitmq/exchanges/*/*/message_stats/confirm_details/rate: {}
      #/rabbitmq/exchanges/*/*/message_stats/publish_in: {}
      #/rabbitmq/exchanges/*/*/message_stats/publish_in_details/rate: {}
      #/rabbitmq/exchanges/*/*/message_stats/publish_out: {}
      #/rabbitmq/exchanges/*/*/message_stats/publish_out_details/rate: {}
      #/rabbitmq/nodes/*/disk_free: {}
      #/rabbitmq/nodes/*/disk_free_details/rate: {}
      #/rabbitmq/nodes/*/fd_used: {}
      #/rabbitmq/nodes/*/fd_used_details/rate: {}
      #/rabbitmq/nodes/*/io_read_avg_time: {}
      #/rabbitmq/nodes/*/io_read_avg_time_details/rate: {}
      #/rabbitmq/nodes/*/io_read_bytes: {}
      #/rabbitmq/nodes/*/io_read_bytes_details/rate: {}
      #/rabbitmq/nodes/*/io_read_count: {}
      #/rabbitmq/nodes/*/io_read_count_details/rate: {}
      #/rabbitmq/nodes/*/io_seek_avg_time: {}
      #/rabbitmq/nodes/*/io_seek_avg_time_details/rate: {}
      #/rabbitmq/nodes/*/io_seek_count: {}
      #/rabbitmq/nodes/*/io_seek_count_details/rate: {}
      #/rabbitmq/nodes/*/io_sync_avg_time: {}
      #/rabbitmq/nodes/*/io_sync_avg_time_details/rate: {}
      #/rabbitmq/nodes/*/io_sync_count: {}
      #/rabbitmq/nodes/*/io_sync_count_details/rate: {}
      #/rabbitmq/nodes/*/io_write_avg_time: {}
      #/rabbitmq/nodes/*/io_write_avg_time_details/rate: {}
      #/rabbitmq/nodes/*/io_write_bytes: {}
      #/rabbitmq/nodes/*/io_write_bytes_details/rate: {}
      #/rabbitmq/nodes/*/io_write_count: {}
      #/rabbitmq/nodes/*/io_write_count_details/rate: {}
      #/rabbitmq/nodes/*/memory/atom: {}
      #/rabbitmq/nodes/*/memory/binary: {}
      #/rabbitmq/nodes/*/memory/code: {}
      #/rabbitmq/nodes/*/memory/connection_channels: {}
      #/rabbitmq/nodes/*/memory/connection_other: {}
      #/rabbitmq/nodes/*/memory/connection_readers: {}
      #/rabbitmq/nodes/*/memory/connection_writers: {}
      #/rabbitmq/nodes/*/memory/mgmt_db: {}
      #/rabbitmq/nodes/*/memory/mnesia: {}
      #/rabbitmq/nodes/*/memory/msg_index: {}
      #/rabbitmq/nodes/*/memory/other_ets: {}
      #/rabbitmq/nodes/*/memory/other_proc: {}
      #/rabbitmq/nodes/*/memory/other_system: {}
      #/rabbitmq/nodes/*/memory/plugins: {}
      #/rabbitmq/nodes/*/memory/queue_procs: {}
      #/rabbitmq/nodes/*/memory/queue_slave_procs: {}
      #/rabbitmq/nodes/*/memory/total: {}
      #/rabbitmq/nodes/*/mem_used: {}
      #/rabbitmq/nodes/*/mem_used_details/rate: {}
      #/rabbitmq/nodes/*/mnesia_disk_tx_count: {}
      #/rabbitmq/nodes/*/mnesia_disk_tx_count_details/rate: {}
      #/rabbitmq/nodes/*/mnesia_ram_tx_count: {}
      #/rabbitmq/nodes/*/mnesia_ram_tx_count_details/rate: {}
      #/rabbitmq/nodes/*/proc_used: {}
      #/rabbitmq/nodes/*/proc_used_details/rate: {}
      #/rabbitmq/nodes/*/queue_index_read_count: {}
      #/rabbitmq/nodes/*/queue_index_read_count_details/rate: {}
      #/rabbitmq/nodes/*/queue_index_write_count: {}
      #/rabbitmq/nodes/*/queue_index_write_count_details/rate: {}
      #/rabbitmq/nodes/*/sockets_used: {}
      #/rabbitmq/nodes/*/sockets_used_details/rate: {}
      #/rabbitmq/queues/*/*/consumers: {}
      #/rabbitmq/queues/*/*/disk_reads: {}
      #/rabbitmq/queues/*/*/disk_writes: {}
      #/rabbitmq/queues/*/*/memory: {}
      #/rabbitmq/queues/*/*/message_bytes: {}
      #/rabbitmq/queues/*/*/message_bytes_persistent: {}
      #/rabbitmq/queues/*/*/message_bytes_ram: {}
      #/rabbitmq/queues/*/*/message_bytes_ready: {}
      #/rabbitmq/queues/*/*/message_bytes_unacknowledged: {}
      #/rabbitmq/queues/*/*/messages: {}
      #/rabbitmq/queues/*/*/messages_details/rate: {}
      #/rabbitmq/queues/*/*/messages_persistent: {}
      #/rabbitmq/queues/*/*/messages_ram: {}
      #/rabbitmq/queues/*/*/messages_ready: {}
      #/rabbitmq/queues/*/*/messages_ready_details/rate: {}
      #/rabbitmq/queues/*/*/messages_ready_ram: {}
      #/rabbitmq/queues/*/*/message_stats/disk_reads: {}
      #/rabbitmq/queues/*/*/message_stats/disk_reads_details/rate: {}
      #/rabbitmq/queues/*/*/message_stats/publish: {}
      #/rabbitmq/queues/*/*/message_stats/publish_details/rate: {}
      #/rabbitmq/queues/*/*/messages_unacknowledged: {}
      #/rabbitmq/queues/*/*/messages_unacknowledged_details/rate: {}
      #/rabbitmq/queues/*/*/messages_unacknowledged_ram: {}
      #/rabbitmq/vhosts/*/messages: {}
      #/rabbitmq/vhosts/*/messages_acknowledged: {}
      #/rabbitmq/vhosts/*/messages_acknowledged_details/rate: {}
      #/rabbitmq/vhosts/*/messages_details/rate: {}
      #/rabbitmq/vhosts/*/messages_ready: {}
      #/rabbitmq/vhosts/*/messages_ready_details/rate: {}
      #/rabbitmq/vhosts/*/message_stats/confirm: {}
      #/rabbitmq/vhosts/*/message_stats/confirm_details/rate: {}
      #/rabbitmq/vhosts/*/message_stats/deliver_get: {}
      #/rabbitmq/vhosts/*/message_stats/deliver_get_details/rate: {}
      #/rabbitmq/vhosts/*/message_stats/get_no_ack: {}
      #/rabbitmq/vhosts/*/message_stats/get_no_ack_details/rate: {}
      #/rabbitmq/vhosts/*/message_stats/publish: {}
      #/rabbitmq/vhosts/*/message_stats/publish_details/rate: {}
      #/rabbitmq/vhosts/*/messages_unacknowledged: {}
      #/rabbitmq/vhosts/*/messages_unacknowledged_details/rate: {}
    publish:
      - plugin_name: publisher-appoptics
        config:
          period: 60
          floor_seconds: 60
