---
version: 1
schedule:
  # Run every minute
  type: cron
  interval: "0 * * * * *"
workflow:
  collect:
    metrics:
      /nagios_exec/*/all: {}
    publish:
      - plugin_name: publisher-appoptics
        config:
          period: 60
          floor_seconds: 60
