---
version: 1
schedule:
  # Run every minute
  type: cron
  interval: "0 * * * * *"
deadline: "60s"
workflow:
  collect:
    metrics:
      /system/cpu/guest: {}
      /system/cpu/idle: {}
      /system/cpu/iowait: {}
      /system/cpu/user: {}
      /system/cpu/system: {}
      /system/cpu/interrupt: {}
      /system/cpu/steal: {}
      /system/cpu/utilization: {}
      /system/load/1: {}
      /system/load/5: {}
      /system/load/15: {}
      /system/load/1_rel: {}
      /system/load/5_rel: {}
      /system/load/15_rel: {}
      /system/mem/buffered: {}
      /system/mem/cached: {}
      /system/mem/free: {}
      /system/mem/used: {}
      /system/mem/total: {}
      /system/mem/inactive: {}
      /system/mem/wired: {}
      /system/mem/percent/free: {}
      /system/mem/percent/used: {}
      /system/swap/total: {}
      /system/swap/percent/free: {}
      /system/swap/percent/used: {}
      /system/disk/*/percent/free: {}
      /system/disk/*/percent/used: {}
      /system/disk/*/bytes/total: {}
      /system/io/*/bytes/read: {}
      /system/io/*/bytes/write: {}
      /system/io/*/ops/read: {}
      /system/io/*/ops/write: {}
      /system/io/*/time/read: {}
      /system/io/*/time/write: {}
      /system/net/*/bytes/rx: {}
      /system/net/*/bytes/tx: {}
      /system/net/*/packets/rx: {}
      /system/net/*/packets/tx: {}
    publish:
      - plugin_name: publisher-appoptics
        config:
          period: 60
          floor_seconds: 60
