Vagrant.configure("2") do |config|
  #Vagrant Image to use
  config.vm.box = "ubuntu/xenial64"
  #hostname for vm
  config.vm.hostname = "saltmaster"
  #network configuration
  #config.vm.network "private_network", type: "dhcp", virtualbox__intnet: "intnet", auto_config: "false"
  config.vm.network "private_network", ip: "172.28.128.50"
  #map local shares
  config.vm.synced_folder "../../saltstack/file_root/salt", "/srv/salt"
  config.vm.synced_folder "../../saltstack/file_root/pillar", "/srv/pillar"
  config.vm.synced_folder "../../hosts", "/srv/hosts"
  config.vm.synced_folder "share", "/srv/share"
  #virtualbox configuration
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
    vb.name = "saltmaster"

### Salt Key cleanup job:
    config.vm.provision "shell", inline: <<-SHELL
      sudo cp -p /srv/share/keymgmt.sh /etc/cron.hourly/keymgmt.sh
      sudo crontab /srv/share/cronjob
#      sudo sed -i 's/dhcp/static\n   address 172.28.128.50\n   netmask 255.255.255.0/g' 50-cloud-init.cfg
#     sudo ip addr flush enp0s8
    SHELL

end
  #salt configuration
  config.vm.provision :salt do |salt|
    salt.install_master = true
    salt.no_minion = false
    salt.verbose = true
    salt.colorize = true
    salt.install_type = "stable"
    salt.master_config = "../../saltstack/config/master"
    salt.minion_config = "../../saltstack/config/master"
    salt.master_key = ".keys/salt/saltmaster.pem"
    salt.master_pub = ".keys/salt/saltmaster.pub"
    salt.minion_key = ".keys/salt/saltmaster.pem"
    salt.minion_pub = ".keys/salt/saltmaster.pub"
    salt.seed_master = {saltmaster: '.keys/salt/saltmaster.pub'}
    salt.run_highstate = true
end
  config.vm.post_up_message = "press enter to complete setup..."
end
