Vagrant.configure("2") do |config|
  #Vagrant Image to use
  config.vm.box = "centos/7"
  #hostname for vm
  config.vm.hostname = "lab-centos-897"
  #network configuration
  config.vm.network "private_network", type: "dhcp"
  #map local shares
  config.vm.synced_folder "../../saltstack/file_root/salt", "/srv/salt"
  config.vm.synced_folder "share", "/srv/share"
  #enable networking on centos minimal distros
  config.vm.provision "shell", inline: <<-SHELL
    sudo systemctl enable NetworkManager
    sudo systemctl start NetworkManager
  SHELL
  #virtualbox configuration
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.name="lab-centos-897"
    vb.memory = "1024"
end
  #salt configuration
  config.vm.provision :salt do |salt|
  salt.install_type = "stable"
  salt.verbose = true
  salt.colorize = true
  salt.minion_config = "../../saltstack/config/master.d/minion"
  salt.minion_id = "lab-centos-897"
  salt.minion_key = "../../saltstack/config/keygen/lab-centos-897.pem"
  salt.minion_pub = "../../saltstack/config/keygen/lab-centos-897.pub"
  salt.run_highstate = true
end
 config.vm.post_up_message = "press enter to complete setup..."
end