Vagrant.configure("2") do |config|
  #Vagrant Image to use
  config.vm.box = "ubuntu/xenial64"
  #hostname for vm
  config.vm.hostname = "lab-ubuntu-859"
  #network configuration
  config.vm.network "private_network", type: "dhcp"
  #map local shares
  config.vm.synced_folder "../../saltstack/file_root/salt", "/srv/salt"
  config.vm.synced_folder "share", "/srv/share"
  #virtualbox configuration
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.name="lab-ubuntu-859"
    vb.memory = "512"
end
  #salt configuration
  config.vm.provision :salt do |salt|
  salt.install_type = "stable"
  salt.verbose = true
  salt.colorize = true
  salt.minion_config = "../../saltstack/config/master.d/minion"
  salt.minion_id = "lab-ubuntu-859"
  salt.minion_key = "../../saltstack/config/keygen/lab-ubuntu-859.pem"
  salt.minion_pub = "../../saltstack/config/keygen/lab-ubuntu-859.pub"
  salt.run_highstate = true
end
 config.vm.post_up_message = "press enter to complete setup..."
end